# Assignment - Solving Linear Equations

**<div style="text-align: right"> [TOTAL SCORE: 45]</div>**

In this assignment, you will apply all that you learned about solving linear systems of equations in this Unit, along with Kirchoff's Law, to optimize the traffic flow through a junction in Baneshwor.

## The Problem

As more and more people migrate to large cities, managing traffic in cities is a common problem in cities all over the world. In this assignment, we aim to optimize the traffic flow through a junction in Baneshor, where this problem is especially pronounced.

Our target here is to find the number of vehicles that should be allowed to cross through a junction made of four one way roads, so that the number of vehicles crossing through is maximized, and the traffic flow is smooth. 

Lets call the the number of vehicles per hour the (mph). In this assignment, we will find the optimum mph for this particular network of roads.

Look at the figure below. We know the number of vehicles that leave the junctions A and C in an hour, and we also know the number of vehicles that enter the junctions B and D in an hour. But we do not know the number of vehicles travelling in the roads between these junctions that is optimum.

<figure>
  <center>
    <img src='https://storage.googleapis.com/codehub-data/6-A-2-lineq1.jpg'/>
  </center>
</figure>

## Mathematical Model

In this section, we will first model the problem using a system of linear equations and then solve this system using two methods:
1. Gauss Elimination
2. PLU Factorization


#### Assumptions
In order to simplify our model, lets make some reasonable assumptions about the traffic through this junction.

1. The number of vehicles leaving each intersection is always equal to the number of vehicles leaving the intersection.

2. All the roads in this system are one-way, with the arrows indicating the direction of traffic flow.

### Formulating a Linear System

We use Kirchoff's law to model the network in order to formulate a system of linear equations.

#### Kirchoff's law:
Kirchoff's law states that for any node (junction) in an electrical circuit, the sum of currents flowing into that node is equal to the sum of currents flowing out of that node. In our case, the network of roads is equivalent to an electrical circuit and number of vehicles per hour (vph) is equaivalent to current. 

This allows us to formulate the following system of linear equations:

**At intersection A:** Traffic in $=x_1+x_2$ , traffic out $=150+300$, thus, $x_1+x_2=450$

**At intersection B:** Traffic in $=100+250$ , traffic out $=x_1+x_4$, thus, $x_1+x_4=350$

**At intersection C:** Traffic in $=x_3+x_4$ , traffic out $=240+100$, thus, $x_3+x_4=340$

**At intersection D:** Traffic in $=250+190$ , traffic out $=x_2+x_3$, thus, $x_2+x_3=440$

Lets summarize all of these in the four equations below:

$$x_1+x_2=450$$
$$x_1+x_4=350$$
$$x_3+x_4=340$$
$$x_2+x_3=440$$



### 1. Import required libraries
Run the cell below to import the required libraries.

In [54]:
import numpy as np
from numpy import linalg

## Exercise 1 - System Representation

**<div style="text-align: right"> [SCORE: 2]</div>**

In this exercise, you will represent the above system of equations in the general form $A \vec x = \vec b$.

**Task:** Create the required coefficient matrix A and vector $\vec b$ using NumPy, and assign them to the variables `A` and `b` respectively.

In [55]:
# Create Matrix A of order 4 x 4
A=None
# YOUR CODE HERE
A=np.array([[1,1,0,0],
        [1,0,0,1],
        [0,0,1,1],
          [0,1,1,0]])
#Create column vector b of order 4 x 1
b=None
# YOUR CODE HERE
b= np.array([[450],[350],[340],[440]])

In [56]:
print(f'A={A}\n')
print(f'b={b}')
assert A.shape==(4,4)
assert b.shape==(4,1)

A=[[1 1 0 0]
 [1 0 0 1]
 [0 0 1 1]
 [0 1 1 0]]

b=[[450]
 [350]
 [340]
 [440]]


## Exercise 2 - Gauss Elimination

Now that we have a system of equations set up, we can use Gauss elimination to solve this system.

Now we use Gauss Elimination method to solve this system.

### Question 1 - Permutation matrix $P_{12}$

**<div style="text-align: right"> [SCORE: 2]</div>**

**Task:** Create the permutation matrix $P_{12}$ to exchange 1st and 2nd row so that it is easier to solve the equations and also calculate A and $\vec b$ after aplying the permutation.

In [57]:
P12 = [
    [0,1,0,0],
    [1,0,0,0],
    [0,0,1,0],
    [0,0,0,1]
]

# YOUR CODE HERE
A=np.matmul(P12,A)
b=np.matmul(P12,b)

In [58]:
assert P12 is not None
print(f'P12={A}')
print(f'A={A}')
print(f'b={b}')


P12=[[1 0 0 1]
 [1 1 0 0]
 [0 0 1 1]
 [0 1 1 0]]
A=[[1 0 0 1]
 [1 1 0 0]
 [0 0 1 1]
 [0 1 1 0]]
b=[[350]
 [450]
 [340]
 [440]]


### Question 2: Elimination matrices $E_{21}, E_{31}$ and $E_{41}$

**<div style="text-align: right"> [SCORE: 5]</div>**

**Task:**  Write the elimination matrices $E_{21}, E_{31} and E_{41}$ to obtain the first pivot column and also the matrix A and $\vec b$ after performing these eliminations.


In [59]:
E21=[
    [0,0,0,0],
    [1,0,0,0],
    [0,0,0,0],
    [0,0,0,0]
]
E31=[
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0]
]
E41=[
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0]
]
A= A
b= b
# YOUR CODE HERE
A=A-np.matmul(E21,A)
b=b-np.matmul(E21,b)
A=A-np.matmul(E31,A)
b=b-np.matmul(E31,b)
A=A-np.matmul(E41,A)
b=b-np.matmul(E41,b)


In [60]:
print(f'E21={E21}')
print(f'E31={E31}')
print(f'E41={E41}')
print(f'A={A}')
print(f'b={b}')



E21=[[0, 0, 0, 0], [1, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
E31=[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
E41=[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
A=[[ 1  0  0  1]
 [ 0  1  0 -1]
 [ 0  0  1  1]
 [ 0  1  1  0]]
b=[[350]
 [100]
 [340]
 [440]]


### Question 3: Elimination Matrices $E_{32}$ and $E_{42}$

**<div style="text-align: right"> [SCORE: 5]</div>**

**Task:**  Write the elimination matrices $E_{32}$ and $E_{42}$ to obtain the second pivot column and also the matrix A and $\vec b$ after performing these eliminations.

In [ ]:
E32=None
E42=None
A=A
b=b

# YOUR CODE HERE
raise NotImplementedError()


In [ ]:
print(f'E32={E32}')
print(f'E42={E42}')
print(f'A={A}')
print(f'b={b}')



### Question 4: Elimination Matrix $E_{43}$

**<div style="text-align: right"> [SCORE: 5]</div>**

**Task:**  Write the elimination matrix $E_{43}$ to obtain the third pivot column and and also the final row echelon matrix R and $\vec b$ after performing these eliminations.

In [ ]:
E43=None
R=None
b=b

# YOUR CODE HERE
raise NotImplementedError()


In [ ]:
print(f'E43={E43}')
print(f'R={R}')
print(f'b={b}')



### Question 5: Rank of $R$

**<div style="text-align: right"> [SCORE: 2]</div>**

**Task:**  Find rank of `R` and assign it to `rank`.


In [ ]:
rank=None
# YOUR CODE HERE
raise NotImplementedError()


In [ ]:
print(f'Rank of the matrix R is {rank}.')


### Question 6: Free Variables

**<div style="text-align: right"> [SCORE: 2]</div>**

**Task:**  Find the number of free variables and assign it to `num_free`. Also find free variables if any and put it in the list `free`. For example, `free=['x1','x3']`.


In [ ]:
num_free=None
free=None
# YOUR CODE HERE
raise NotImplementedError()


In [ ]:
print(f'number of free variables = {num_free}')

You must have found out that there is a free variable, $x_4$. Therefore, this system has infinitely many solutions.

The system of equations that corresponds to the row echelon form $R\vec x=\vec b$ is

$$x_1+x_4=b_1$$

$$x_2-x_4=b_2$$

$$x_3+x_4=b_3$$

We express all the other vaariables in terms of $x_4$. 

$$x_1=-x_4+b_1$$

$$x_2=x_4+b_2$$

$$x_3=-x_4+b_3$$

We said that this system of the equations has infinitely many solutions, but what does this actually mean? It means that there are infinitely many ways to manage the traffic flow in this junction. 

Consider the stretch DC. It may be desirable to have as little traffic flow as possible along this stretch. The flow of traffic in each stretch in the junction can be controlled using things like traffic lights and speed limit signs. According to the model, the third equation in the system shows that $x_3$ will be a minimum when $x_4$ is as large as possible, as long as it does not exceeds $b_3$. The largest value can be assumed without causing negative values of $x_1$ or $x_2$, i.e. must be less than $b_1$. So, for convenience we choose the value of $x_4=100$ since it satisifies all the conditions. 

### Question 7: Calculating a Solution

**<div style="text-align: right"> [SCORE: 4]</div>**

**Task:**  Using $x_4=100$ and the values of $b_1,b_2,b_3$ obtained previously in $\vec b$, calculate $x_1, x_2, x_3$.

In [ ]:
b1=None
b2=None
b3=None

x1=None
x2=None
x3=None
x4=100

# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
print(f'b1:{b1}\nb2:{b2}\nb3:{b3}\n')
print(f'x1:{x1}\nx2:{x2}\nx3:{x3}\nx4:{x4}')



Therefore, to keep the traffic flowing x3  must be routed between D and C, x1 between A and B, x2 between A and D and x4 between B and C.

## Exercise 3: Elimination by PLU Factorization

In the previous exercise, we solved the given system of equations using Gauss Elimination. In this exercse, we will do the same thing, but this time using PLU factorization. 

$PA=LU$

where,

- P is a permutation matrix

- L is a lower trianglar matrix

- U = R is an upper triangular matrix

- A is the initial coefficient matrix

Let us revisit the system of linear equations obtained previously:

$$x_1+x_2=450$$

$$x_1+x_4=350$$

$$x_3+x_4=340$$

$$x_2+x_3=440$$


### Question 1: System Representation

**<div style="text-align: right"> [SCORE: 2]</div>**

**Task:** Re-represent the given system of equations in the form $A\vec x = \vec b$ by creating the required coefficient matrix A and vector $\vec b$ using numpy arrays. We need to this because while solving the questions in the first exercise, the variables `A` and `b` had been changed many times.

In [ ]:
# Create Matrix A of order 4 x 4
A=None
# YOUR CODE HERE
raise NotImplementedError()

#Create column vector b of order 4 x 1
b=None
# YOUR CODE HERE
raise NotImplementedError()


In [ ]:
print(f'A={A}\n')
print(f'b={b}')
assert A.shape==(4,4)
assert b.shape==(4,1)

Now, since $PA=LU$, we can write


$\quad \quad A\vec x=\vec b$<br> 
$\implies PA\vec x=P\vec b$<br> 
$\implies LU\vec x=P\vec b$

Consider,

$\quad \quad U\vec x=\vec c=\begin{bmatrix}c_1\\c_2\\c_3\\c_4\end{bmatrix}$ Then, <br>

$\implies L\vec c=P\vec b$<br> 


### Question 2: Permutation and Lower Triangular Matrix

**<div style="text-align: right"> [SCORE: 4]</div>**
**Task:** Use the permutation matrix above and obtain $P\vec b$. Also obain L using the elimination matrices caluclated above.

In [ ]:
Pb=None
L=None

# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
print(f'L={L}\n')
print(f'Pb={Pb}')




### Question 3: Upper Triangular Matrix

**<div style="text-align: right"> [SCORE: 1]</div>**
**Task:** Solve $L\vec c=P\vec b$ to obtain $\vec c$. Then obtain U using the row echelon form R.

In [ ]:
U=None
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
print(f'c={c}\n')
print(f'U={U}')

The system of equations that corresponds to $U\vec x=\vec c$ is

$$x_1+x_4=c_1$$

$$x_2-x_4=c_2$$

$$x_3+x_4=c_3$$

We express other equations in terms of $x_4$. 

$$x_1=-x_4+c_1$$

$$x_2=x_4+c_2$$

$$x_3=-x_4+c_3$$

We take $x_4=100$ since it is a free variable

### Question 4: Solving for $\vec x$
**<div style="text-align: right"> [SCORE: 4]</div>**
**Task:** Solve $U\vec x = \vec c$ to obtain the final solution $\vec x$.

In [ ]:
c1=None
c2=None
c3=None

x1=None
x2=None
x3=None
x4=100

# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
print(f'c1:{c1}\nc2:{c2}\nc3:{c3}\n')
print(f'x1:{x1}\nx2:{x2}\nx3:{x3}\nx4:{x4}')



Let us suppose the data is collected again in 2019 in the same streets and the new data is as shown in Figure 2

<figure>
  <center>
   <img src='https://storage.googleapis.com/codehub-data/6-A-2-lineq2.jpg'/>
  </center>
</figure>

So, the system of equations for the model was formulated using Kirchoff's law as follows:

**At intersection A:** Traffic in $=x_1+x_2$ , traffic out $=150+250$, thus, $x_1+x_2=400$

**At intersection B:** Traffic in $=130+220$ , traffic out $=x_1+x_4$, thus, $x_1+x_4=350$

**At intersection C:** Traffic in $=x_3+x_4$ , traffic out $=210+150$, thus, $x_3+x_4=360$

**At intersection D:** Traffic in $=200+200$ , traffic out $=x_2+x_3$, thus, $x_2+x_3=400$

The constraints were written as a system of linear equations as follows:

$$x_1+x_2=400$$

$$x_1+x_4=350$$

$$x_3+x_4=360$$

$$x_2+x_3=400$$

Using PLU Factorization, it is easy to solve these system of equations since only $\vec b$ has changed. So, the value of P, L and U can be reused to calculate $\vec x$ quickly.

### Question 5: Setting Up A System For New Data
**<div style="text-align: right"> [SCORE: 2]</div>**
**Tesk:** So, now create the new vector $\vec b$ using numpy arrays and use the permutation matrix calculated above and obtain $P\vec b$.

In [ ]:
b=None
Pb=None

#Create column vector b of order 4 x 1 and also caluclate Pb
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
print(f'b={b}\n')
print(f'Pb={Pb}')

### Question 6: Finding $C$
**<div style="text-align: right"> [SCORE: 1]</div>**
**Task:** Solve $L\vec c=P\vec b$ to obtain $\vec c$.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
print(f'c={c}\n')
print(f'U={U}')

The system of equations that corresponds to $U\vec x=\vec c$ is

$$x_1+x_4=c_1$$

$$x_2-x_4=c_2$$

$$x_3+x_4=c_3$$

We express other equations in terms of $x_4$. 

$$x_1=-x_4+c_1$$

$$x_2=x_4+c_2$$

$$x_3=-x_4+c_3$$

We take $x_4=100$ since it is a free variable

### Question 7: Solving For $X$
**<div style="text-align: right"> [SCORE: 4]</div>**
**Task:** Solve $U\vec x = \vec c$ to obtain the final solution $\vec x$.

In [ ]:
c1=None
c2=None
c3=None

x1=None
x2=None
x3=None
x4=100

# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
print(f'c1:{c1}\nc2:{c2}\nc3:{c3}\n')
print(f'x1:{x1}\nx2:{x2}\nx3:{x3}\nx4:{x4}')



Hence, PLU Factorization can be used to calculate the solutions easily when data is changed. 