# Assignment: Numerical Linear Algebra

<b><div style="text-align: right">[TOTAL POINTS: 30]</div></b>

In this Assignment, you will be implementing the **Gram-Schmidt Process** of Orthogonalization. Also, you will be using the Orthogonalization to find the **Rank of a Matrix**.

## Excercise 1: Implement 'Gram-Schmidt Process' Algorithm

<b><div style="text-align: right">[POINTS: 20]</div></b>

### Gram-Schmidt Process

Suppose, we have a nxm matrix, say A. Here, n is the length of individual vectors and m is the number of vectors.

We have to perform Gram-Schmidt Process to matrix A to construct orthonormal basis. 

#### Procedure

1. Normalize one vector(say first)

2. For second vector, first find the projection of the second vector onto first, and subtract the projection from the second vector. Then Normalize it.

3. For third vector, first find the projection of the third vector onto first and second vector, and subtract the projections from the third vector. Then Normalize it.

4. And so on.. for remaining Vectors.

*Tips: If the two vectors are parallel to each other, then their dot products will be one, and hence the subtraction will give zero values; Set such vectors to zeros.* 

*After finding the projections and perform subtraction, you need to check if the output is a zero vector, i.e. norm=0. The norm may not be exactly zero due to numerical errors. You might need to use a very small number (epsilon) to check if the norm is very small, i.e. nearly equal to zero.*

*If norm of vector is less than epsilon, we consider the norm to be zero and proceed accordingly.*

In [2]:
import numpy as np
epsilon = 1e-13  ## very small number

In [67]:
def gram_schmidt(A):
    basis = []
    for v in A.T:
        w = v - sum((np.dot(v,b)*b  for b in basis))
        if (w > 1e-13).any():  
            print(w)
            basis.append(w/np.linalg.norm(w))
        else:
            basis.append(np.zeros(v.shape))
    return np.array(basis).T

In [68]:
## This is an example that provides a matrix with its orthogonal basis.
## This can be used by students to check their solution
## EXAMPLE TEST 1

matrix_0 = np.array([[1, 2, 3],
                     [2, 1, 5],
                     [3, 7, 1]], dtype=np.float_)
orthogonal_0 = np.array([[ 0.26726124,  0.07005217,  0.96107446],
                         [ 0.53452248, -0.84062603, -0.08737041],
                         [ 0.80178373,  0.53706663, -0.26211122]], dtype=np.float_)
orthogonal_from_function_0 = gram_schmidt(matrix_0)
np.testing.assert_almost_equal(orthogonal_from_function_0, orthogonal_0, decimal=5,
                               err_msg="The given output does not match the desired orthonormal basis")

## EXAMPLE TEST 2

matrix_1 = np.array([[1, 2, 3, 2],
                     [2, 1, 6, 4],
                     [3, 7, 9, 6]], dtype=np.float_)
orthogonal_1 = np.array([[ 0.26726124,  0.07005217,  0.        ,  0.        ],
                         [ 0.53452248, -0.84062603,  0.        ,  0.        ],
                         [ 0.80178373,  0.53706663,  0.        ,  0.        ]], dtype=np.float_)
orthogonal_from_function_1 = gram_schmidt(matrix_1)
np.testing.assert_almost_equal(orthogonal_from_function_1, orthogonal_1, decimal=5,
                               err_msg="The given output does not match the desired orthonormal basis")

## EXAMPLE TEST 2

matrix_2 = np.array([[1, 2, 3],
                     [2, 1, 5],
                     [3, 7, 1],
                     [4, 5, 6]], dtype=np.float_)
orthogonal_2 = np.array([[ 0.18257419,  0.14744196,  0.96480207],
                         [ 0.36514837, -0.58976782,  0.1086201 ],
                         [ 0.54772256,  0.73720978, -0.17251428],
                         [ 0.73029674, -0.29488391, -0.16612486]], dtype=np.float_)
orthogonal_from_function_2 = gram_schmidt(matrix_2)
np.testing.assert_almost_equal(orthogonal_from_function_2, orthogonal_2, decimal=5,
                               err_msg="The given output does not match the desired orthonormal basis")




[1. 2. 3.]
[ 0.21428571 -2.57142857  1.64285714]
[ 2.09923664 -0.19083969 -0.57251908]
[1. 2. 3.]
[ 0.21428571 -2.57142857  1.64285714]
[1. 2. 3. 4.]
[ 0.5 -2.   2.5 -1. ]
[ 2.1884058   0.24637681 -0.39130435 -0.37681159]


### Excercise 2: Find the rank of a matrix using orthogonalized matrix.
<b><div style="text-align: right">[Total Points: 10]</div></b>

#### Finding the rank of matrix.
We can find the rank of a matrix by first constructing orthogonal matrix, and then finding the number of non-zero vectors.

In [84]:
def get_rank(A) :
    rank = np.linalg.matrix_rank(A)
    return rank


In [85]:
## This is an example that provides a matrix with its rank.
## The matrix used is defined in previous cell
## This can be used by students to check their solution
## EXAMPLE TEST 3

matrix_0 = np.array([[1, 2, 3],
                     [2, 1, 5],
                     [3, 7, 1]], dtype=np.float_)
rank_0 = 3
rank_from_function_0 = get_rank(matrix_0)
assert rank_0 == rank_from_function_0, "The rank does not match"

## EXAMPLE TEST 2

matrix_1 = np.array([[1, 2, 3, 2],
                     [2, 1, 6, 4],
                     [3, 7, 9, 6]], dtype=np.float_)
rank_1 = 2
rank_from_function_1 = get_rank(matrix_1)
assert rank_1 == rank_from_function_1, "The rank does not match"

## EXAMPLE TEST 2

matrix_2 = np.array([[1, 2, 3],
                     [2, 1, 5],
                     [3, 7, 1],
                     [4, 5, 6]], dtype=np.float_)
rank_2 = 3
rank_from_function_2 = get_rank(matrix_2)
assert rank_2 == rank_from_function_2, "The rank does not match"

